name: Fastlane P12 Grabber
on:
  workflow_dispatch:
    inputs:
      two_factor_code:
        description: 'กรอกรหัส 2FA 6 ตัว (ถ้าเด้งในมือถือ)'
        required: false

jobs:
  fastlane_run:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Fastlane
        run: brew install fastlane

      - name: Grab Certificates
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }} # เผื่อไว้สำหรับคนติด 2FA หนักๆ
          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: "" # ใส่เบอร์ถ้าต้องการ (ไม่จำเป็น)
          # ส่งรหัส 2FA เข้าไปผ่าน Input
          FASTLANE_OTP: ${{ github.event.inputs.two_factor_code }}
        run: |
          mkdir -p output
          # สั่งรัน Fastlane lane ที่เราเขียนไว้
          fastlane ios get_certs || echo "ติดปัญหาบางอย่าง"

      - name: Save to Repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add output/
          git commit -m "Got certs via Fastlane" || echo "No files found"
          git push
